config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/bienvenida', to: 'home#index' #home es el nombre del controlador y index la accion(metodo)

  root to: 'home#index'


  get "articles/user/:user_id", to: "articles#from_author"
  get 'articles', to: 'articles#index'
  get 'articles/new', to: 'articles#new', as: :new_articles
  get 'articles/:id', to: 'articles#show' # :id es un comodin para pasarle el articulo que queremos consultar
  get 'articles/:id/edit', to: 'articles#edit'
  patch 'articles/:id', to: 'articles#update', as: :article
  post 'articles', to: 'articles#create'
  delete 'articles/:id', to: 'articles#destroy'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_rich_text :content #Le indicamos al modelo que tiene un campo texto enriquecido y le ponemos un identificador con nombre arbitratio (:content)
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :find_article, except: [:new, :create, :index, :from_author]
    before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
    #Cada que se ejecute una accion, antes se va a ejecutar find_article

    def index
        @articles = Article.all
    end
    
    def show
    end

    def edit
    end

    def update
        @article.update(title: params[:article][:title], content: params[:article][:content])
        # ORM es lo que usamos para pasar cosas a la DB
        redirect_to @article
    end

    def new
        @article = Article.new #crear un nuevo objeto tipo Articulo vacio
        # Se crea la variable con @ para poder acceder a la variable desde la vista
    end

    def create #Guardar lo que hallamos recibido del formulario del metodo new
        @article = current_user.articles.create(title: params[:article][:title], content: params[:article][:content])
        # Estamos creando un hash (JSON) para que lo guarde en el modelo(db)
        # Recibimos lo que va a venir de new con params y creamos el articulo en la db
        
        redirect_to @article
    end

    def destroy
        @article.destroy
        redirect_to root_path
    end

    def from_author
        @user = User.find(params[:user_id])
    end

    def find_article
        @article = Article.find(params[:id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user! #Force an user login

  def index
    #Aun estando vacia rails busca en la carpeta views una subcarpeta llamada igual que el controlador y una archivo que se llame igual que la accion, ahi tenemos la muesta index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/articles/_article.html.erb
<div class="card padding margin-top">
        <h3 class="text-uppercase"> <%= article.title %> </h3>
    <p class="text-secondary"> <%= article.created_at %> </p>
    <%= link_to "Ver más", article%>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: @article, local: true) do |form|  %>
<%# form_with es un metodo para construir un formulario ademas recibe un bloque de ruby (do end) %>
<%# lo que le mandemos en model es lo que va a llenar en los campos declarados mas abajo %>    
    <br><br>
    <div class="field">
        <%= form.label :title  %>
        <%= form.text_field :title  %>
        <%# desde text_field se toma la variable title y la manda al objeto articulo %>
    </div>
    <br><br>
    <div class="field">
        <%= form.label :content %>
        <%= form.rich_text_area :content %>
        <%# Este es control de ActionText %>
    </div>
    <div>
        <%= form.submit %>
    </div>
<%end %>

app/views/articles/edit.html.erb
<div class="small-container center-block">
    <%= render "articles/form" %>
</div>

app/views/articles/from_author.html.erb
<div class="large-container center-block">
    <h1> Artículos publicados por <%= @user.email %> </h1>

    <%= render @user.articles %>
</div>

app/views/articles/index.html.erb
<div class="large-container center-block">
    <h1> Mis artículos </h1>
    <%= render @articles %>
</div>

app/views/articles/new.html.erb
<div class="small-container center-block">
    <%= render "articles/form" %>
</div>

app/views/articles/show.html.erb
<div class="large-container center-block">
    <br> </br>

    <h1> <%= @article.title %> </h1>
    <div>
        <p>Escrito por <strong><%=@article.user.email %></strong> </p>
    </div>

    <div>

        <%= @article.content %>

    </div>

    <div>
        <%=link_to "Eliminate Article", @article, method: :delete %>
    </div>
</div>

app/views/home/index.html.erb
<%# Controlada por la accion(metodo) index, en el controlador home %>
<h1>Hola <%= current_user.email %> </h1>

<%= link_to "Inicio", root_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Proyect1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice%>
      <br>
      <p class="notice alert-primary"><%= notice %></p>
    <%end%>

    <% if alert%>
      <br>
      <p class="alert alert-danger"><%= alert %></p>
    <%end%>

    <%= render "partials/nav" %>
    <%= yield %>
  </body>
</html>

app/views/partials/_nav.html.erb
<% if !alert && !notice %>
    <br>
<%end%>

<nav class="nav bg-light padding"> 
    <li class="nav-item">
        <%= link_to "Inicio", root_path, class:"nav-link" %>
    </li>
    <li class="nav-item">
        <%= link_to "Articulos", articles_path, class:"nav-link" %>
    </li>
    <li class="nav-item">
        <%= link_to "Escribir", new_articles_path, class:"nav-link" %>
    </li>

    <%if user_signed_in? %>
        <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class:"nav-link" %>
        </li>
    <% else %>
        <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
        </li>
    <% end %>

</nav>